language: node_js
node_js:
  - "10"
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
script:
  - npm test
  - npm run build
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npm run publish
  on:
    branch: master
